apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: job-set
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: job-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
